# Generated by Django 4.2.14 on 2024-08-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="생성일시",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True, db_comment="수정일시"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="라벨 이름",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_comment="주소록 소유자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "label",
                "db_table_comment": "라벨",
            },
        ),
    ]
