# Generated by Django 4.2.14 on 2024-08-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        ("label", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="생성일시",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True, db_comment="수정일시"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="저장한 이름",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="저장한 이메일",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_comment="저장한 전화번호",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        db_comment="저장한 회사",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        db_comment="저장한 직책",
                        max_length=50,
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True, db_comment="메모"
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        db_comment="프로필 이미지 URL",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="주소",
                        max_length=100,
                    ),
                ),
                (
                    "birthday",
                    models.DateTimeField(
                        blank=True,
                        db_comment="생일",
                        null=True,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        db_comment="웹사이트 URL",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_comment="주소록 소유자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contactbook",
                "db_table_comment": "주소록",
            },
        ),
        migrations.CreateModel(
            name="ContactLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="생성일시",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True, db_comment="수정일시"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        db_comment="주소록",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labeled_contact",
                        to="contactbook.contactbook",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        db_comment="라벨",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labeled_contact",
                        to="label.label",
                    ),
                ),
            ],
            options={
                "db_table": "contactbook_label",
                "db_table_comment": "주소록에 있는 연락처의 라벨링을 관리하는 테이블",
            },
        ),
        migrations.AddIndex(
            model_name="contactbook",
            index=models.Index(
                fields=["name"],
                name="contactbook_name_5f92a9_idx",
            ),
        ),
    ]
