# Generated by Django 4.2.14 on 2024-08-03 12:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("contactbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbook",
            name="birthday",
            field=models.DateField(
                blank=True, db_comment="생일", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_comment="저장한 전화번호",
                max_length=20,
                region="KR",
            ),
        ),
    ]
