# Generated by Django 4.2.14 on 2024-08-03 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("label", "0001_initial"),
        (
            "contactbook",
            "0002_alter_contactbook_birthday_alter_contactbook_phone",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contactlabel",
            unique_together={("contact", "label")},
        ),
    ]
